"""Generated cross-bundle command and leaf index.

Do not edit. `just update-generated` regenerates this from every skill's
static COMMANDS manifest."""

from __future__ import annotations

COMMAND_BUNDLES: dict[str, tuple[str, ...]] = {
    'accept': ('cook',),
    'age-route': ('affinage', 'age'),
    'append-attempt': ('hard-cheese',),
    'artifact-path': ('age', 'briesearch', 'cook', 'mold'),
    'baseline': ('cook',),
    'batch-resolve': ('melt',),
    'budget-check': ('briesearch',),
    'checkpoint': ('wheypoint',),
    'conflict-pick': ('melt',),
    'conflict-summary': ('melt',),
    'curd-count': ('mold',),
    'debug-tag-sweep': ('pasteurize',),
    'detect-squash-residue': ('melt',),
    'doctor': ('easy-cheese-setup',),
    'domain-model-target': ('cure', 'mold'),
    'finalize': ('mold',),
    'findings': ('age', 'cook', 'cure'),
    'freshness-check': ('hard-cheese',),
    'gate-graph': ('mold',),
    'gates': ('age', 'cook', 'cure'),
    'global': ('easy-cheese-setup',),
    'ground-check': ('briesearch',),
    'handoff': ('age', 'cook', 'cure', 'wheypoint'),
    'html-report': ('age',),
    'lint': ('wheypoint',),
    'list': ('wheypoint',),
    'local': ('easy-cheese-setup',),
    'lockfile-resolve': ('melt',),
    'log': ('wheypoint',),
    'manifest-update': ('cook',),
    'milknado': ('cook',),
    'mode': ('cook',),
    'normalize': ('cook',),
    'normalize-planner': ('mold',),
    'pasteurize-route': ('pasteurize',),
    'paths': ('age', 'cook', 'cure'),
    'phase-decision': ('cook',),
    'post-reply': ('affinage',),
    'pr-plan-to-branches': ('cook',),
    'pr-status': ('affinage',),
    'prepare': ('cook',),
    'press-route': ('press',),
    'press-telemetry': ('press',),
    'rank-hunks': ('hard-cheese',),
    'read-handoff-slug': ('age', 'cook', 'cure'),
    'render-html': ('age', 'cook', 'cure', 'mold'),
    'repro-rerun': ('pasteurize',),
    'research-layout': ('briesearch',),
    'resolve': ('wheypoint',),
    'resubmit': ('cook',),
    'review-instructions': ('age',),
    'review-lock': ('age',),
    'review-plan-check': ('age',),
    'review-surface': ('affinage', 'age'),
    'schema': ('wheypoint',),
    'severity': ('age',),
    'show': ('wheypoint',),
    'slugify': ('age', 'cook', 'cure'),
    'stack-tools': ('plate',),
    'taste-test': ('mold',),
    'turns': ('wheypoint',),
    'validate': ('cook', 'wheypoint'),
    'validate-decomposition': ('cook',),
    'validate-manifest': ('cook',),
    'validate-pr-plan': ('cook',),
    'validate-publication': ('plate',),
    'validate-spec': ('mold',),
    'wheypoint-resolve': ('affinage', 'age', 'cook', 'cure', 'plate', 'press'),
    'wiring-topo-sort': ('cook',),
    'worktree': ('cook',),
    'write-handoff-artifact': ('age', 'cook', 'cure', 'press'),
}

LEAF_OWNERS: dict[str, tuple[tuple[str, str], ...]] = {
    'bucket': (('age', 'severity'),),
    'check-files': (('cook', 'manifest-update'),),
    'classify': (('age', 'gates'), ('cook', 'gates'), ('cure', 'gates')),
    'compute': (('age', 'severity'),),
    'create': (('cook', 'worktree'),),
    'dispatch': (('age', 'handoff'), ('cook', 'handoff'), ('cure', 'handoff'), ('wheypoint', 'handoff')),
    'domain-model-target': (('age', 'paths'), ('cook', 'paths'), ('cure', 'paths')),
    'existing': (('age', 'paths'), ('cook', 'paths'), ('cure', 'paths')),
    'from-task': (('age', 'slugify'), ('cook', 'slugify'), ('cure', 'slugify')),
    'harvest': (('cook', 'worktree'),),
    'list': (('age', 'paths'), ('cook', 'paths'), ('cure', 'paths')),
    'parse': (('age', 'handoff'), ('cook', 'handoff'), ('cure', 'handoff'), ('wheypoint', 'handoff')),
    'parse-selection': (('age', 'findings'), ('cook', 'findings'), ('cure', 'findings')),
    'render': (('age', 'handoff'), ('cook', 'handoff'), ('cure', 'handoff'), ('wheypoint', 'handoff')),
    'render-brief': (('age', 'findings'), ('cook', 'findings'), ('cure', 'findings')),
    'render-table': (('age', 'findings'), ('cook', 'findings'), ('cure', 'findings')),
    'resolve': (('age', 'paths'), ('cook', 'paths'), ('cure', 'paths')),
    'set-curd-status': (('cook', 'manifest-update'),),
    'set-phase': (('cook', 'manifest-update'),),
    'set-post-review': (('cook', 'manifest-update'),),
    'set-wiring-status': (('cook', 'manifest-update'),),
    'slugify': (('age', 'paths'), ('cook', 'paths'), ('cure', 'paths')),
    'teardown': (('cook', 'worktree'),),
    'validate': (('age', 'paths'), ('cook', 'paths'), ('cure', 'paths')),
}
